// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYZ7dSyDBJ60ZS9pNlofJzh_No5VfPmmM',
    appId: '1:330428788627:web:93a715d892b8909bf24266',
    messagingSenderId: '330428788627',
    projectId: 'unbarmherzigkeit-auth',
    authDomain: 'unbarmherzigkeit-auth.firebaseapp.com',
    storageBucket: 'unbarmherzigkeit-auth.firebasestorage.app',
    measurementId: 'G-4SSR7VTCV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9apknVlzPhwj_XpxIyYZ3N2jPrdpS5NQ',
    appId: '1:330428788627:android:32af2a8ef38ace90f24266',
    messagingSenderId: '330428788627',
    projectId: 'unbarmherzigkeit-auth',
    storageBucket: 'unbarmherzigkeit-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw8CuY0MVVyrGNo4M0j4DR9DX9PQ0v66A',
    appId: '1:330428788627:ios:57e365868262268ff24266',
    messagingSenderId: '330428788627',
    projectId: 'unbarmherzigkeit-auth',
    storageBucket: 'unbarmherzigkeit-auth.firebasestorage.app',
    iosBundleId: 'com.example.projektUnbarmherzigkeit',
  );
}
